# Generated by Django 4.2.3 on 2023-11-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_rename_license_number_hairsalon_licence_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
