# Generated by Django 4.2.3 on 2023-11-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_hairsalon_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairsalon',
            name='licence',
        ),
    ]
