# Generated by Django 4.2.3 on 2023-11-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_hairsalon_groups_hairsalon_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='licence',
            field=models.ImageField(default='default_license.jpg', upload_to='licences/'),
        ),
    ]
