# Generated by Django 4.2.7 on 2023-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_hairsalon_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairsalon',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
