# Generated by Django 4.2.3 on 2023-11-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_alter_hairsalon_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
