# Generated by Django 4.2.7 on 2023-11-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_hairsalon_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.hairsalon')),
            ],
        ),
    ]
