# Generated by Django 4.2.7 on 2023-11-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.CharField(default='1700894205660', max_length=20, unique=True),
        ),
    ]
