# Generated by Django 4.2.7 on 2023-11-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_alter_service_price_alter_service_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
    ]
