# Generated by Django 4.2.7 on 2023-11-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_remove_service_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.hairsalon'),
        ),
    ]
