# Generated by Django 4.2.7 on 2023-11-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_alter_service_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.hairsalon'),
        ),
    ]
