# Generated by Django 4.2.7 on 2023-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_alter_service_salon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylist_name', models.CharField(max_length=100)),
            ],
        ),
    ]
