# Generated by Django 4.2.7 on 2023-12-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.hairsalon'),
        ),
    ]
