# Generated by Django 4.2.7 on 2023-12-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0021_timeslot_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.timeslot')),
            ],
        ),
    ]
