# Generated by Django 4.2.7 on 2023-12-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0022_bookedtimeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedTimeSlot',
        ),
    ]
