# Generated by Django 4.2.7 on 2024-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0023_delete_bookedtimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
