# Generated by Django 4.2.3 on 2023-11-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_hairsalon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HairSalon',
        ),
    ]
