# Generated by Django 4.2.3 on 2023-11-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_delete_hairsalon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
