# Generated by Django 4.2.7 on 2023-12-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0020_timeslot_salon'),
        ('booking', '0004_customuser_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.stylist')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
