# Generated by Django 4.2.7 on 2023-12-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
