# Generated by Django 4.2.7 on 2023-12-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_appointment_salon_appointment_salon_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='salon_location',
            new_name='salon_name',
        ),
    ]
