# Generated by Django 4.2.7 on 2023-12-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_appointment_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service_price',
        ),
    ]
