# Generated by Django 4.2.7 on 2023-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_order_end_time_order_salon_order_salon_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time_slot',
            new_name='day',
        ),
    ]
