# Generated by Django 4.2.7 on 2023-12-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_rename_time_slot_order_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salon_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
    ]
