# Generated by Django 4.2.7 on 2023-12-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_order_salon_order_salon_name_order_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot_day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot_start_time',
            field=models.TimeField(null=True),
        ),
    ]
