# Generated by Django 4.2.7 on 2023-12-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='time_slot_date',
        ),
    ]
