# Generated by Django 4.2.7 on 2023-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
    ]
