# Generated by Django 4.2.7 on 2023-12-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booked', 'New Booked'), ('salonRequest', 'New SalonRequest')], max_length=20),
        ),
    ]
