# Generated by Django 4.2.7 on 2023-12-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booked', 'New Booked'), ('salonRegisterRequest', 'New SalonRegisterRequest')], max_length=20),
        ),
    ]
