# Generated by Django 4.2.7 on 2023-12-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0023_delete_bookedtimeslot'),
        ('booking', '0032_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='to_user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='from_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='salonUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to='salon.hairsalon'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_type',
            field=models.CharField(choices=[('user', 'USER'), ('salon', 'SALON'), ('admin', 'ADMIN')], max_length=20, null=True),
        ),
    ]
