# Generated by Django 4.2.7 on 2023-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_rename_to_user_notification_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
