# Generated by Django 4.2.7 on 2023-12-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booked', 'New Booked'), ('pending', 'New Pending'), ('completed', 'New Completed'), ('cancelled', 'New Cancelled')], max_length=20),
        ),
    ]
