# Generated by Django 4.2.7 on 2023-12-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_remove_notification_sender_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], max_length=20, null=True),
        ),
    ]
